require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'

require 'json'
podfile_properties = JSON.parse(File.read('./Podfile.properties.json')) rescue {}

target 'rkApp' do

 
  config = use_native_modules!

  use_react_native!(
    
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
   
  )

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  pod 'react-native-blur', :path => '../node_modules/@react-native-community/blur'

  pod 'react-native-video', :path => '../node_modules/react-native-video'

  # pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'ReactNativeART', :path => '../node_modules/@react-native-community/art'

  pod 'RNSnackbar', :path => '../node_modules/react-native-snackbar'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  post_install do |installer|
    flipper_post_install(installer)
    react_native_post_install(installer)
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
